/* ==========================================================================
   BKK Motorbike Rental - Fleet & Application Mock Data
   ========================================================================== */

const FLEET_DATA = [
  // --- 10 STANDARD BIKES (฿300/d, ฿1900/w, ฿5500/m) ---
  {
    id: 'BKK-STD-01',
    name: 'Honda Click 160 ABS',
    model: 'Honda Click 160',
    tier: 'standard',
    cc: 160,
    fuelType: 'Gasoline 95/Gasohol',
    storage: '18 Liters',
    transmission: 'Automatic CVT',
    rates: { daily: 300, weekly: 1900, monthly: 5500 },
    deposit: { domestic: 1000, international: 2000 },
    image: 'assets/images/click160.jpg',
    status: 'available', // available | rented | maintenance
    plateNumber: '1กข-4920 กทม.',
    iotDeviceId: 'IOT-CL160-01',
    fuelLevel: 95,
    batteryVoltage: 12.6,
    odometerKm: 3420,
    currentLocation: { name: 'Sathorn Main Hub (MRT Lumphini)', lat: 13.7258, lng: 100.5432 }
  },
  {
    id: 'BKK-STD-02',
    name: 'Honda Click 160 Sport',
    model: 'Honda Click 160',
    tier: 'standard',
    cc: 160,
    fuelType: 'Gasoline 95',
    storage: '18 Liters',
    transmission: 'Automatic CVT',
    rates: { daily: 300, weekly: 1900, monthly: 5500 },
    deposit: { domestic: 1000, international: 2000 },
    image: 'assets/images/click160.jpg',
    status: 'rented',
    plateNumber: '2ขค-8812 กทม.',
    iotDeviceId: 'IOT-CL160-02',
    fuelLevel: 70,
    batteryVoltage: 12.4,
    odometerKm: 6120,
    currentLocation: { name: 'Sukhumvit Soi 11 (BTS Nana)', lat: 13.7431, lng: 100.5562 }
  },
  {
    id: 'BKK-STD-03',
    name: 'Honda Click 125i Smart',
    model: 'Honda Click 125i',
    tier: 'standard',
    cc: 125,
    fuelType: 'Gasohol 91/95',
    storage: '18 Liters',
    transmission: 'Automatic',
    rates: { daily: 300, weekly: 1900, monthly: 5500 },
    deposit: { domestic: 1000, international: 2000 },
    image: 'assets/images/click160.jpg',
    status: 'available',
    plateNumber: '3งจ-3341 กทม.',
    iotDeviceId: 'IOT-CL125-03',
    fuelLevel: 100,
    batteryVoltage: 12.8,
    odometerKm: 1840,
    currentLocation: { name: 'Khaosan Road Station', lat: 13.7592, lng: 100.4975 }
  },
  {
    id: 'BKK-STD-04',
    name: 'Yamaha Scoopy-i Club 12',
    model: 'Yamaha Scoopy-i',
    tier: 'standard',
    cc: 110,
    fuelType: 'Gasohol 91/95',
    storage: '15.4 Liters',
    transmission: 'Automatic',
    rates: { daily: 300, weekly: 1900, monthly: 5500 },
    deposit: { domestic: 1000, international: 2000 },
    image: 'assets/images/click160.jpg',
    status: 'available',
    plateNumber: '4ฉช-9014 กทม.',
    iotDeviceId: 'IOT-SCP-04',
    fuelLevel: 88,
    batteryVoltage: 12.5,
    odometerKm: 4210,
    currentLocation: { name: 'Chulalongkorn University Hub', lat: 13.7371, lng: 100.5312 }
  },
  {
    id: 'BKK-STD-05',
    name: 'Yamaha Scoopy-i Prestige',
    model: 'Yamaha Scoopy-i',
    tier: 'standard',
    cc: 110,
    fuelType: 'Gasohol 91/95',
    storage: '15.4 Liters',
    transmission: 'Automatic',
    rates: { daily: 300, weekly: 1900, monthly: 5500 },
    deposit: { domestic: 1000, international: 2000 },
    image: 'assets/images/click160.jpg',
    status: 'rented',
    plateNumber: '5ซฌ-1192 กทม.',
    iotDeviceId: 'IOT-SCP-05',
    fuelLevel: 55,
    batteryVoltage: 12.3,
    odometerKm: 8900,
    currentLocation: { name: 'Thonglor Soi 10 (BTS Thong Lo)', lat: 13.7321, lng: 100.5821 }
  },
  {
    id: 'BKK-STD-06',
    name: 'Honda Lead 125 Touring',
    model: 'Honda Lead 125',
    tier: 'standard',
    cc: 125,
    fuelType: 'Gasohol 95',
    storage: '37 Liters (Fits 2 Helmets)',
    transmission: 'Automatic',
    rates: { daily: 300, weekly: 1900, monthly: 5500 },
    deposit: { domestic: 1000, international: 2000 },
    image: 'assets/images/click160.jpg',
    status: 'available',
    plateNumber: '6ญฎ-7821 กทม.',
    iotDeviceId: 'IOT-LEAD-06',
    fuelLevel: 92,
    batteryVoltage: 12.7,
    odometerKm: 2150,
    currentLocation: { name: 'Asok Interchange (BTS Asok / MRT Sukhumvit)', lat: 13.7368, lng: 100.5604 }
  },
  {
    id: 'BKK-STD-07',
    name: 'Honda Click 160 Urban',
    model: 'Honda Click 160',
    tier: 'standard',
    cc: 160,
    fuelType: 'Gasoline 95',
    storage: '18 Liters',
    transmission: 'Automatic',
    rates: { daily: 300, weekly: 1900, monthly: 5500 },
    deposit: { domestic: 1000, international: 2000 },
    image: 'assets/images/click160.jpg',
    status: 'available',
    plateNumber: '7ฏฐ-4419 กทม.',
    iotDeviceId: 'IOT-CL160-07',
    fuelLevel: 80,
    batteryVoltage: 12.5,
    odometerKm: 5120,
    currentLocation: { name: 'Ari Neighborhood (BTS Ari)', lat: 13.7798, lng: 100.5448 }
  },
  {
    id: 'BKK-STD-08',
    name: 'Yamaha Scoopy-i Urban',
    model: 'Yamaha Scoopy-i',
    tier: 'standard',
    cc: 110,
    fuelType: 'Gasohol 91/95',
    storage: '15.4 Liters',
    transmission: 'Automatic',
    rates: { daily: 300, weekly: 1900, monthly: 5500 },
    deposit: { domestic: 1000, international: 2000 },
    image: 'assets/images/click160.jpg',
    status: 'maintenance',
    plateNumber: '8ฑฒ-6502 กทม.',
    iotDeviceId: 'IOT-SCP-08',
    fuelLevel: 40,
    batteryVoltage: 11.9,
    odometerKm: 12050,
    currentLocation: { name: 'Central Service Depot (Sathorn)', lat: 13.7258, lng: 100.5432 }
  },
  {
    id: 'BKK-STD-09',
    name: 'Honda Click 125i Eco',
    model: 'Honda Click 125i',
    tier: 'standard',
    cc: 125,
    fuelType: 'Gasohol 95',
    storage: '18 Liters',
    transmission: 'Automatic',
    rates: { daily: 300, weekly: 1900, monthly: 5500 },
    deposit: { domestic: 1000, international: 2000 },
    image: 'assets/images/click160.jpg',
    status: 'rented',
    plateNumber: '9ณด-9182 กทม.',
    iotDeviceId: 'IOT-CL125-09',
    fuelLevel: 65,
    batteryVoltage: 12.4,
    odometerKm: 7600,
    currentLocation: { name: 'Silom Complex (BTS Sala Daeng)', lat: 13.7285, lng: 100.5342 }
  },
  {
    id: 'BKK-STD-10',
    name: 'Honda Lead 125 Metro',
    model: 'Honda Lead 125',
    tier: 'standard',
    cc: 125,
    fuelType: 'Gasohol 95',
    storage: '37 Liters',
    transmission: 'Automatic',
    rates: { daily: 300, weekly: 1900, monthly: 5500 },
    deposit: { domestic: 1000, international: 2000 },
    image: 'assets/images/click160.jpg',
    status: 'available',
    plateNumber: '1ตถ-2039 กทม.',
    iotDeviceId: 'IOT-LEAD-10',
    fuelLevel: 90,
    batteryVoltage: 12.6,
    odometerKm: 3100,
    currentLocation: { name: 'Phra Khanong (BTS Phra Khanong)', lat: 13.7154, lng: 100.5925 }
  },

  // --- 10 PREMIUM BIKES (฿450/d, ฿2800/w, ฿9500/m) ---
  {
    id: 'BKK-PRM-01',
    name: 'Honda Forza 350 HSTC',
    model: 'Honda Forza 350',
    tier: 'premium',
    cc: 330,
    fuelType: 'Gasoline 95',
    storage: '48 Liters (2 Helmets + Bag)',
    transmission: 'Automatic eSP+ CVT',
    rates: { daily: 450, weekly: 2800, monthly: 9500 },
    deposit: { domestic: 3000, international: 5000 },
    image: 'assets/images/forza350.jpg',
    status: 'available',
    plateNumber: '2ทธ-8890 กทม.',
    iotDeviceId: 'IOT-FZ350-01',
    fuelLevel: 100,
    batteryVoltage: 12.9,
    odometerKm: 1400,
    currentLocation: { name: 'Sathorn Main Hub (MRT Lumphini)', lat: 13.7258, lng: 100.5432 }
  },
  {
    id: 'BKK-PRM-02',
    name: 'Honda Forza 350 Touring',
    model: 'Honda Forza 350',
    tier: 'premium',
    cc: 330,
    fuelType: 'Gasoline 95',
    storage: '48 Liters',
    transmission: 'Automatic CVT',
    rates: { daily: 450, weekly: 2800, monthly: 9500 },
    deposit: { domestic: 3000, international: 5000 },
    image: 'assets/images/forza350.jpg',
    status: 'rented',
    plateNumber: '3นบ-1029 กทม.',
    iotDeviceId: 'IOT-FZ350-02',
    fuelLevel: 82,
    batteryVoltage: 12.7,
    odometerKm: 4200,
    currentLocation: { name: 'EmQuartier Sukhumvit (BTS Phrom Phong)', lat: 13.7303, lng: 100.5698 }
  },
  {
    id: 'BKK-PRM-03',
    name: 'Yamaha XMAX 300 Connected',
    model: 'Yamaha XMAX 300',
    tier: 'premium',
    cc: 292,
    fuelType: 'Gasoline 95',
    storage: '45 Liters',
    transmission: 'Automatic CVT',
    rates: { daily: 450, weekly: 2800, monthly: 9500 },
    deposit: { domestic: 3000, international: 5000 },
    image: 'assets/images/forza350.jpg',
    status: 'available',
    plateNumber: '4ปผ-7712 กทม.',
    iotDeviceId: 'IOT-XM300-03',
    fuelLevel: 94,
    batteryVoltage: 12.8,
    odometerKm: 2800,
    currentLocation: { name: 'Asok Interchange (BTS Asok)', lat: 13.7368, lng: 100.5604 }
  },
  {
    id: 'BKK-PRM-04',
    name: 'Yamaha XMAX 300 Sport',
    model: 'Yamaha XMAX 300',
    tier: 'premium',
    cc: 292,
    fuelType: 'Gasoline 95',
    storage: '45 Liters',
    transmission: 'Automatic CVT',
    rates: { daily: 450, weekly: 2800, monthly: 9500 },
    deposit: { domestic: 3000, international: 5000 },
    image: 'assets/images/forza350.jpg',
    status: 'rented',
    plateNumber: '5ฝพ-3390 กทม.',
    iotDeviceId: 'IOT-XM300-04',
    fuelLevel: 60,
    batteryVoltage: 12.5,
    odometerKm: 8100,
    currentLocation: { name: 'Iconsiam Riverside Pier', lat: 13.7267, lng: 100.5108 }
  },
  {
    id: 'BKK-PRM-05',
    name: 'Vespa Sprint 150 i-Get ABS',
    model: 'Vespa Sprint 150',
    tier: 'premium',
    cc: 150,
    fuelType: 'Gasoline 95',
    storage: 'Classic Underseat',
    transmission: 'Automatic CVT',
    rates: { daily: 450, weekly: 2800, monthly: 9500 },
    deposit: { domestic: 3000, international: 5000 },
    image: 'assets/images/vespa.jpg',
    status: 'available',
    plateNumber: '6ฟภ-5521 กทม.',
    iotDeviceId: 'IOT-VSP-05',
    fuelLevel: 98,
    batteryVoltage: 12.7,
    odometerKm: 1950,
    currentLocation: { name: 'Thonglor Soi 10 (BTS Thong Lo)', lat: 13.7321, lng: 100.5821 }
  },
  {
    id: 'BKK-PRM-06',
    name: 'Vespa Primavera 150 Classic',
    model: 'Vespa Primavera 150',
    tier: 'premium',
    cc: 150,
    fuelType: 'Gasoline 95',
    storage: 'Classic Underseat',
    transmission: 'Automatic',
    rates: { daily: 450, weekly: 2800, monthly: 9500 },
    deposit: { domestic: 3000, international: 5000 },
    image: 'assets/images/vespa.jpg',
    status: 'available',
    plateNumber: '7มย-9914 กทม.',
    iotDeviceId: 'IOT-VSP-06',
    fuelLevel: 85,
    batteryVoltage: 12.6,
    odometerKm: 3400,
    currentLocation: { name: 'Khaosan Road Station', lat: 13.7592, lng: 100.4975 }
  },
  {
    id: 'BKK-PRM-07',
    name: 'Honda Forza 350 Dark Edition',
    model: 'Honda Forza 350',
    tier: 'premium',
    cc: 330,
    fuelType: 'Gasoline 95',
    storage: '48 Liters',
    transmission: 'Automatic eSP+',
    rates: { daily: 450, weekly: 2800, monthly: 9500 },
    deposit: { domestic: 3000, international: 5000 },
    image: 'assets/images/forza350.jpg',
    status: 'rented',
    plateNumber: '8รล-4402 กทม.',
    iotDeviceId: 'IOT-FZ350-07',
    fuelLevel: 75,
    batteryVoltage: 12.6,
    odometerKm: 5900,
    currentLocation: { name: 'Siam Paragon Hub (BTS Siam)', lat: 13.7462, lng: 100.5347 }
  },
  {
    id: 'BKK-PRM-08',
    name: 'Yamaha XMAX 300 Tech Max',
    model: 'Yamaha XMAX 300',
    tier: 'premium',
    cc: 292,
    fuelType: 'Gasoline 95',
    storage: '45 Liters',
    transmission: 'Automatic CVT',
    rates: { daily: 450, weekly: 2800, monthly: 9500 },
    deposit: { domestic: 3000, international: 5000 },
    image: 'assets/images/forza350.jpg',
    status: 'available',
    plateNumber: '9วศ-1290 กทม.',
    iotDeviceId: 'IOT-XM300-08',
    fuelLevel: 92,
    batteryVoltage: 12.8,
    odometerKm: 2200,
    currentLocation: { name: 'Ari Station (BTS Ari)', lat: 13.7798, lng: 100.5448 }
  },
  {
    id: 'BKK-PRM-09',
    name: 'Vespa Sprint S 150 Mint',
    model: 'Vespa Sprint 150',
    tier: 'premium',
    cc: 150,
    fuelType: 'Gasoline 95',
    storage: 'Classic Underseat',
    transmission: 'Automatic',
    rates: { daily: 450, weekly: 2800, monthly: 9500 },
    deposit: { domestic: 3000, international: 5000 },
    image: 'assets/images/vespa.jpg',
    status: 'rented',
    plateNumber: '1ษส-8391 กทม.',
    iotDeviceId: 'IOT-VSP-09',
    fuelLevel: 68,
    batteryVoltage: 12.4,
    odometerKm: 4800,
    currentLocation: { name: 'Ekkamai Gateway (BTS Ekkamai)', lat: 13.7192, lng: 100.5849 }
  },
  {
    id: 'BKK-PRM-10',
    name: 'Honda Forza 350 Luxury Silver',
    model: 'Honda Forza 350',
    tier: 'premium',
    cc: 330,
    fuelType: 'Gasoline 95',
    storage: '48 Liters',
    transmission: 'Automatic',
    rates: { daily: 450, weekly: 2800, monthly: 9500 },
    deposit: { domestic: 3000, international: 5000 },
    image: 'assets/images/forza350.jpg',
    status: 'available',
    plateNumber: '2หฬ-6601 กทม.',
    iotDeviceId: 'IOT-FZ350-10',
    fuelLevel: 96,
    batteryVoltage: 12.8,
    odometerKm: 1650,
    currentLocation: { name: 'Sathorn Main Hub (MRT Lumphini)', lat: 13.7258, lng: 100.5432 }
  }
];

const LOCATIONS_DATA = [
  { id: 'sathorn', name: 'Sathorn Main Station', area: 'MRT Lumphini (Exit 1)', lat: 13.7258, lng: 100.5432 },
  { id: 'asok', name: 'Asok Interchange Station', area: 'BTS Asok / MRT Sukhumvit', lat: 13.7368, lng: 100.5604 },
  { id: 'khaosan', name: 'Khaosan Road Station', area: 'Old Town & Tourist Hub', lat: 13.7592, lng: 100.4975 },
  { id: 'thonglor', name: 'Thonglor Station', area: 'Sukhumvit Soi 55 / BTS Thong Lo', lat: 13.7321, lng: 100.5821 },
  { id: 'ari', name: 'Ari Station', area: 'BTS Ari / Phahonyothin', lat: 13.7798, lng: 100.5448 },
  { id: 'delivery', name: 'Doorstep Hotel/Condo Delivery', area: 'Any location in Bangkok (within 15km)', fee: 200 }
];

const INITIAL_REVIEWS_DATA = [
  {
    id: 'rev-01',
    name: 'Alexandre Meyer',
    email: 'alexandre.m@gmail.com',
    role: 'Expat Software Lead from France',
    bike: 'Honda Forza 350 ABS',
    rating: 5,
    title: 'Top tier maxi-scooter with zero paperwork hassle',
    comment: 'Rented the Honda Forza 350 for 2 months. The digital PromptPay checkout and instant unlock key are brilliant! Way smoother than traditional Bangkok shops.',
    avatar: 'AM',
    date: '2 days ago',
    verifiedGoogle: true
  },
  {
    id: 'rev-02',
    name: 'Ploy Siriwat',
    email: 'ploy.chula@gmail.com',
    role: 'Chulalongkorn University Student',
    bike: 'Honda Scoopy Club12',
    rating: 5,
    title: 'Affordable student package and fast refund',
    comment: 'The student discount and Scoopy monthly package saved me so much transit time and money. Very transparent with zero hidden deposit tricks!',
    avatar: 'PS',
    date: '1 week ago',
    verifiedGoogle: true
  },
  {
    id: 'rev-03',
    name: 'Marcus & Sarah',
    email: 'marcus.nomad@gmail.com',
    role: 'Digital Nomads from Germany',
    bike: 'Honda PCX 160 e:HEV',
    rating: 5,
    title: 'Seamless keyless IoT unlock & pristine helmets',
    comment: 'Best rental experience in Thailand! Verified passport online, scanned PromptPay, and the bike was ready with 2 clean helmets and phone mount.',
    avatar: 'MS',
    date: '2 weeks ago',
    verifiedGoogle: true
  },
  {
    id: 'rev-04',
    name: 'David Jenkins',
    email: 'david.j.uk@gmail.com',
    role: 'Tourist from London, UK',
    bike: 'Vespa Sprint 150 i-Get',
    rating: 5,
    title: 'Riding the Vespa through Old Town was unforgettable!',
    comment: 'The Vespa was showroom condition. Doorstep delivery right to our hotel in Silom arrived exactly on the minute. Super polite team on WhatsApp.',
    avatar: 'DJ',
    date: '3 weeks ago',
    verifiedGoogle: true
  },
  {
    id: 'rev-05',
    name: 'Nattapong K.',
    email: 'nattapong.dev@gmail.com',
    role: 'Local Tech Commuter from Ladprao',
    bike: 'Honda Click 160 ABS',
    rating: 5,
    title: 'Great commuter bike while my car was in the shop',
    comment: 'Click 160 has great punch off the line and huge underseat storage. The smart key phone controller made running errands around Asok effortless.',
    avatar: 'NK',
    date: '1 month ago',
    verifiedGoogle: true
  },
  {
    id: 'rev-06',
    name: 'Elena Rostova',
    email: 'elena.design@gmail.com',
    role: 'Remote Designer from Canada',
    bike: 'Yamaha Grand Filano Hybrid',
    rating: 5,
    title: 'Fuel economy is unbelievable & very quiet engine',
    comment: 'Rented for 14 days while working out of Thonglor cafes. Hybrid engine is whisper quiet and I only spent ฿120 on gas the entire two weeks!',
    avatar: 'ER',
    date: '1 month ago',
    verifiedGoogle: true
  }
];

// Load persisted reviews from localStorage if available, otherwise initialize with baseline data
let REVIEWS_DATA = (() => {
  try {
    if (typeof localStorage !== 'undefined') {
      const saved = localStorage.getItem('bkk_customer_reviews');
      if (saved) {
        const parsed = JSON.parse(saved);
        if (Array.isArray(parsed) && parsed.length > 0) return parsed;
      }
    }
  } catch (e) {
    if (typeof console !== 'undefined' && console.warn) {
      console.warn('Error loading saved reviews from localStorage', e);
    }
  }
  return [...INITIAL_REVIEWS_DATA];
})();

const FAQ_DATA = [
  {
    q_en: 'What documents are required to rent a motorbike?',
    q_th: 'ต้องใช้เอกสารอะไรบ้างในการเช่ามอเตอร์ไซค์?',
    a_en: '1. Original Passport (for tourists/expats) or Thai National ID Card (for Thai citizens).\n2. Valid Driver\'s License or International Driving Permit (IDP).\n3. Security Deposit (฿1,000–฿2,000 for Standard, ฿3,000–฿5,000 for Premium) fully refunded upon safe return.',
    a_th: '1. หนังสือเดินทางตัวจริง (ชาวต่างชาติ) หรือ บัตรประชาชน (คนไทย)\n2. ใบขับขี่ที่ยังไม่หมดอายุ หรือ ใบขับขี่สากล (IDP)\n3. เงินมัดจำประกันความเสียหาย (1,000–2,000 บาท สำหรับ Standard / 3,000–5,000 บาท สำหรับ Premium) คืนเต็มจำนวนเมื่อส่งคืนรถสภาพสมบูรณ์'
  },
  {
    q_en: 'How does the Smart Key / IoT Unlock work?',
    q_th: 'ระบบกุญแจดิจิทัล Smart Key / IoT ปลดล็อกทำงานอย่างไร?',
    a_en: 'Once your booking and payment are confirmed, a secure Digital Key is generated in your app. When standing next to your assigned motorbike, simply tap "Unlock Motorbike" to disarm the immobilizer and start your ride.',
    a_th: 'หลังจากยืนยันการจองและชำระเงินเรียบร้อย คุณจะได้รับกุญแจดิจิทัลในแอป เมื่ออยู่ใกล้รถของคุณ เพียงกดปุ่ม "ปลดล็อกรถ" เพื่อปลดระบบ Immobilizer และสตาร์ทรถได้ทันที'
  },
  {
    q_en: 'Is insurance and helmet included?',
    q_th: 'มีประกันภัยและหมวกกันน็อกรวมอยู่ด้วยหรือไม่?',
    a_en: 'Yes! Every rental includes mandatory Compulsory Third-Party Liability Insurance (Por Ror Bor) and 2 sanitized safety helmets. You can also add our optional Zero-Deductible Damage Waiver.',
    a_th: 'รวมแล้วแน่นอน! ทุกการเช่ามี พ.ร.บ. คุ้มครองบุคคลภายนอก และหมวกกันน็อกทำความสะอาดฆ่าเชื้อ 2 ใบ รวมอยู่ในแพ็กเกจ และสามารถเลือกซื้อประกันคุ้มครองความเสียหายแบบไร้ค่าเสียหายส่วนแรกเพิ่มเติมได้'
  },
  {
    q_en: 'Can I get the motorbike delivered to my hotel or condo?',
    q_th: 'มีบริการจัดส่งรถถึงโรงแรมหรือคอนโดหรือไม่?',
    a_en: 'Yes, we offer doorstep delivery and pickup anywhere in central Bangkok (within 15km of our hubs) for a flat fee of ฿200.',
    a_th: 'มีบริการจัดส่งและรับรถคืนถึงหน้าโรงแรมหรือคอนโดทั่วกรุงเทพฯ ชั้นใน (ระยะทางไม่เกิน 15 กม.) เพียง 200 บาท'
  }
];
